services:
  - type: web
    name: harsh-portfolio
    env: php
    buildCommand: "./render-build.sh"
    startCommand: "heroku-php-apache2 public/"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://harsh-portfolio.onrender.com
